struct Animals* add(struct Animals*, int, int);
void show(struct Animals*, int);
void print_all(struct Animals*, int);
void change(struct Animals*, int);
void change_one_animal(struct Animals*, int);
void partial_change(struct Animals*, int);
int input_int(void);
float input_float(void);
void line(void);
void top(void);
int menu(void);
int correct_input(int);
void search(struct Animals*, int);
void search_by_parameter(struct Animals*, int);
void search_part(struct Animals*, int);
struct Animals* del(struct Animals*, int*);
struct Animals* delete_animal(struct Animals*, int*, int);
void max_sort(struct Animals*, int);
void min_sort(struct Animals*, int);
void sort(struct Animals*, int);
